USE [master]
GO

/****** Object:  Database [CustomerInfo]    Script Date: 2/14/2022 2:12:12 PM ******/
CREATE DATABASE [CustomerInfo]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CustomerInfo', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\CustomerInfo.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CustomerInfo_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\CustomerInfo_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CustomerInfo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CustomerInfo] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CustomerInfo] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CustomerInfo] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CustomerInfo] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CustomerInfo] SET ARITHABORT OFF 
GO

ALTER DATABASE [CustomerInfo] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CustomerInfo] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CustomerInfo] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CustomerInfo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CustomerInfo] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CustomerInfo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CustomerInfo] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CustomerInfo] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CustomerInfo] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CustomerInfo] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CustomerInfo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CustomerInfo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CustomerInfo] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CustomerInfo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CustomerInfo] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CustomerInfo] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CustomerInfo] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CustomerInfo] SET RECOVERY FULL 
GO

ALTER DATABASE [CustomerInfo] SET  MULTI_USER 
GO

ALTER DATABASE [CustomerInfo] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CustomerInfo] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CustomerInfo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CustomerInfo] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CustomerInfo] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CustomerInfo] SET QUERY_STORE = OFF
GO

ALTER DATABASE [CustomerInfo] SET  READ_WRITE 
GO


